const movies = [
  {
    title: '300',
    subtitle: 'Preparem-se para a glória.',
    storyline: 'Em 480 a.C., Leônidas, o rei de Esparta, comanda seu pequeno batalhão de 300 soldados contra um exército de mais de 1 milhão na Batalha das Termópilas.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/qJlsfKtRRvJOKIf6CBZ20SCKcOp.jpg',
  },
  {
    title: '300 - A ascensão do Império',
    subtitle: '',
    storyline: 'Após a morte do pai, Xerxes (Rodrigo Santoro) dá início a uma jornada de vingança e ruma em direção à Grécia, com seu exército sendo liderado por Artemisia (Eva Green). Enquanto os 300 espartanos liderados por Leonidas tantam combater o Deus-Rei, os exércitos do resto da Grécia se unem para uma batalha com as tropas de Artemisia no mar. Themistocles (Sullivan Stapleton) é o responsável por liderar os gregos.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/l9T9hsVca2mh0S29olWRUE3uBpz.jpg',
  },
  {
    title: '20000 Léguas Submarinas',
    subtitle: '',
    storyline: 'Em 1866, o Professor Pierre M. Aronnax e seu assistente Conseil, que estão em São Francisco para pesquisar relatos de um monstro marinho gigante atacando navios no Oceano Pacífico, são convidados a participar de uma expedição para procurar a criatura. Durante a busca, eles e o arpoador Ned Land são lançados ao mar durante um ataque, acabando por descobrir que o monstro é na verdade um submarino pilotado pelo brilhante, mas assombrado, Capitão Nemo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/uClbNT4JtdWwsj4iEvjztL6vb9o.jpg',
  },
  {
    title: 'A Lenda do Tesouro Perdido',
    subtitle: 'As pistas podem estar bem diante de seus olhos.',
    storyline: 'Benjamin Franklin Gates, na busca desenfreada por um lendário tesouro, tem que roubar um dos documentos mais sagrados e protegidos dos EUA, a Declaração de Independência, ou deixar que uma pista fundamental do mistério caia em mãos perigosas.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/5TAQBqvokRt2qHEgi7ipeX1Bif9.jpg',
  },
  {
    title: 'Aprendiz de Feiticeiro',
    subtitle: 'Este é o melhor trabalho do mundo.',
    storyline: 'Balthazar Blake é um feiticeiro que mora em Manhattan. Ele busca defender a cidade de seu arquinimigo, Maxim Horvarth, mas não é capaz de cumprir esta tarefa sozinho. Para tanto ele recruta Dave Stutler, um rapaz comum, mas com um potencial oculto para ser seu aprendiz. Balthazar passa então a ministrar um rápido curso na arte e ciência da magia, de forma a torná-lo seu aliado na luta constante contra as forças de Horvarth.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/cL1nr253DD3668Na0cxfe9B6QRM.jpg',
  },
  {
    title: 'Avatar',
    subtitle: 'Descubra um novo mundo.',
    storyline: 'Apesar de não ter mais os movimentos da perna, o ex-fuzileiro naval Jake Sully ainda sente que pode ser um guerreiro. Sua intuição começa a se tornar realidade quando ele viaja anos-luz até a estação espacial montada no Planeta Pandora. Habitado por grandes seres azuis, os Na´vi, o local tem uma atmosfera fatal para qualquer terrestre. Por isso, oficiais criaram o programa Avatar, em que um corpo biológico, híbrido de humano e Na´vi, pode ser comandado a distância.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/8x4TSGxaIIzTgQXyplBn1Y8mjlX.jpg',
  },
  {
    title: 'Cão de Briga',
    subtitle: 'Soltá-lo pode ser fatal!',
    storyline: 'Desde que Bart tirou Danny da rua, com a idade de 4 anos, sempre o tratou como um cão, treinando-o literalmente para o ataque. Danny é hoje sua grande arma, capaz de se atirar sobre qualquer um com uma simples ordem. Isolado do mundo, Danny não tem outra escolha a não ser aceitar essa existência de animal. Mas as coisas mudam quando ele conhece Sam, um cego que ganha a vida como afinador de pianos. Sam faz Danny descobrir um lado humano que até então lhe era desconhecido.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/clIruzqSTUDM7CnDGANQPMb6vw3.jpg',
  },
  {
    title: 'Código de Conduta',
    subtitle: 'Um homem sem nada a perder é capaz de tudo.',
    storyline: 'Clyde é um dedicado pai de família que testemunha sua esposa e filha serem assassinadas. Um dos culpados ganha liberdade, graças à um acordo feito com o ambicioso promotor Nick. Anos depois o assassino é encontrado morto e Clyde é preso mesmo sem provas concretas contra ele. Para incriminá-lo Nicky vai precisar de uma confissão. Clyde quer apenas denunciar o corrupto sistema judicial nem que para isso tenha que matar todos os envolvidos. Mas, ele já está na cadeia, como o promotor poderá impedi-lo se ele está sempre um passo a frente de todos?',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/pW2PKCDKZ0ocEamVAEDDR3Buup2.jpg',
  },
  {
    title: 'Como perder um homem em 10 dias?',
    subtitle: 'Um deles está mentindo. O outro também.',
    storyline: 'Ben é um publicitário que aposta com o chefe que faz qualquer mulher se apaixonar por ele em dez dias. Se conseguir, será o responsável por uma cobiçada campanha de diamantes. Andie é uma jornalista que, por causa de uma matéria, está decidida a infernizar a vida de qualquer homem que se aproximar. Os dois se conhecem em um bar e escolhem um ao outro como alvo de seus planos totalmente opostos.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/qxwgxjFUtZ3qf7vib9na6tdPfwT.jpg',
  },
  {
    title: 'Coringa',
    subtitle: 'Coloque um sorriso nessa cara.',
    storyline: 'Arthur Fleck trabalha como palhaço para uma agência de talentos e, toda semana, precisa comparecer a uma agente social, devido aos seus conhecidos problemas mentais. Após ser demitido, Fleck reage mal à gozação de três homens em pleno metrô e os mata. Os assassinatos iniciam um movimento popular contra a elite de Gotham City, da qual Thomas Wayne é seu maior representante.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xLxgVxFWvb9hhUyCDDXxRPPnFck.jpg',
  },
  {
    title: 'Darkman',
    subtitle: 'Eles destruíram tudo o que ele tinha, tudo o que ele era. Agora, o crime tem um novo inimigo e a justiça tem uma nova cara.',
    storyline: 'Um brilhante cientista descobre uma forma de produzir pele humana artificialmente. Atacado por criminosos, ele fica desfigurado e recebe um tratamento experimental que o salva. Agora, ele busca vingança contra seus agressores.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/8jXoC81hLq4qXL9Rx2Q1qBlD1rP.jpg',
  },
  {
    title: 'O Grande Dragão Branco',
    subtitle: 'Isso não é um esporte é uma guerra!',
    storyline: 'O soldado americano Frank Dux vai a Hong Kong para ser aceito no Kumite, uma competição de artes marciais altamente secreta e extremamente violenta. Enquanto tenta ganhar acesso ao mundo subterrâneo dos combatentes clandestinos, ele também tem que fugir dos oficiais militares que o consideram um desertor. Depois de suportar um treinamento difícil e começar um romance com a jornalista Janice Kent, é dada a Frank a oportunidade de lutar.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/y9Qp6ngGWc0lxhwNfzrLEtAUE0z.jpg',
  },
  {
    title: 'Gênio Indomável',
    subtitle: 'Agora ele vai conhecer seu par.',
    storyline: 'Em Boston, um jovem de 20 anos (Matt Damon) que já teve algumas passagens pela polícia e servente de uma universidade, revela-se um gênio em matemática e, por determinação legal, precisa fazer terapia, mas nada funciona, pois ele debocha de todos os analistas, até se identificar com um deles.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/AlXkMIEjvk2Npc15zyL0r3P4HBH.jpg',
  },
  {
    title: 'Gladiador',
    subtitle: 'O que fazemos na vida ecoa na eternidade.',
    storyline: 'Nos dias finais do reinado de Marcus Aurelius, o imperador desperta a ira de seu filho Commodus ao tornar pública sua predileção em deixar o trono para Maximus, o comandante do exército romano. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus, que consegue fugir antes de ser pego e passa a se esconder sob a identidade de um escravo e gladiador do Império Romano.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/4DUClyGA6OqjXv6yC0Imf6THGfp.jpg',
  },
  {
    title: 'Um Homem de Família',
    subtitle: 'E se você tivesse uma segunda chance?',
    storyline: 'Jack Campbell um investidor entediado com sua longa vida de solteiro. Um belo dia, ele acorda e começa a imaginar como teria sido sua vida se tivesse se casado com Kate, sua namorada nos tempos de colégio. Até que, repentinamente, Jack acorda e se vê um feliz marido, casado com Kate, pai de duas crianças e levando uma tranquila vida no subúrbio.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/aYe5p1a1JGwY6y3SOFdTHpbOLSA.jpg',
  },
  {
    title: 'A Hora do Rush',
    subtitle: 'As mãos mais rápidas do leste encontra a maior boca do oeste.',
    storyline: 'Quando a filha de um diplomata chinês é sequestrada em Los Angeles, o cônsul chama o inspector Lee em Hong Kong para ajudar o FBI com o caso. O FBI não se importa com Lee e o deixa de lado no Departamento de Polícia de Los Angeles, pedindo ao detetive James Carter que o vigie. Apesar de Lee e Carter não se suportarem, eles resolvem trabalhar juntos para resolver o caso por conta própria ao descobrirem que foram abandonados tanto pelo FBI quanto pela polícia.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/wVWrIJ18BnBuwd9cVjxju5a2Wtl.jpg',
  },
  {
    title: 'Indiana Jones e a Última Cruzada',
    subtitle: 'Ele está de volta em uma nova aventura.',
    storyline: 'O arqueólogo Indiana Jones tem acesso à um misterioso envelope que contém informações sobre a localização do lendário Santo Graal, o cálice que Jesus Cristo teria utilizado na Última Ceia. Quando seu pai, o professor Henry Jones, é sequestrado pelos nazistas, o aventureiro irá embarcar numa missão perigosa para salvá-lo e impedir que a relíquia sagrada caia em mãos erradas.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/vTBem2ZGmLKVgaD3EtJUfMQ9AH1.jpg',
  },
  {
    title: 'Interestelar',
    subtitle: 'O fim da terra não será o nosso fim.',
    storyline: 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/nCbkOyOMTEwlEV0LtCOvCnwEONA.jpg',
  },
  {
    title: 'Invasão à Casa Branca',
    subtitle: 'A segurança da Casa Branca nunca mais será a mesma...',
    storyline: 'O Serviço Secreto dos Estados Unidos conta com a ajuda do ex-segurança particular e amigo pessoal do presidente para resgatar o chefe de Estado e sua família de terroristas coreanos, que os fizeram reféns e assumiram o controle da Casa Branca.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/2JPvshfwo2xhom2Hxu88rOrgt3Q.jpg',
  },
  {
    title: 'Invasão a Londres',
    subtitle: 'A Casa Branca foi só o começo.',
    storyline: 'O primeiro-ministro britânico morre sob circunstâncias misteriosas, e o funeral atrai todos os líderes do mundo ocidental. O agente secreto Mike Banning descobre uma conspiração para assassinar todos os líderes mundiais presentes.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/wazDH9pNQxLzBKCZvN2iMduXxGb.jpg',
  },
  {
    title: 'Irmão Urso',
    subtitle: 'A natureza chama.',
    storyline: 'Em busca de vingança por seu pai ter sido morto por um urso, o índio Kenai acaba sendo amaldiçoado pelos espíritos da floresta e é transformado em um urso. Obrigado a viver sob a nova pele, ele começa a ver a realidade sob a ótica dos animais. Logo faz amizade com outro urso, Koda, mas se vê em apuros quando seu próprio irmão começa a caçá-lo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/fIzn6W7znipa9YcPMr5arsMm2UP.jpg',
  },
  {
    title: 'Kung Fu Panda',
    subtitle: 'Prepare-se para o inacreditável.',
    storyline: 'Po é um panda que trabalha na loja de macarrão da sua família e sonha em transformar-se em um mestre de kung fu. Seu sonho se torna realidade quando, inesperadamente, ele deve cumprir uma profecia antiga e estudar a arte marcial com seus ídolos, os Cinco Furiosos. Po precisa de toda a sabedoria, força e habilidade que conseguir reunir para proteger seu povo de um leopardo da neve malvado.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/xCn3VOST64XpOA8x0gaQkQiZtZY.jpg',
  },
  {
    title: 'Kung Fu Panda 2',
    subtitle: 'Ele vai se empenhar 2 vezes mais!',
    storyline: 'Po (Jack Black) vive o sonho de ser o dragão guerreiro, protegendo o Vale da Paz ao lado dos mestres Shifu (Dustin Hoffman), Tigresa (Angelina Jolie), Macaco (Jackie Chan), Víbora (Lucy Liu), Louva-deus (Seth Rogen) e Garça (David Cross). Sua vida pacata chega ao fim quando surge um novo inimigo, o lorde Chen (Gary Oldman), que possui uma arma secreta capaz de permitir a conquista da China e provocar o fim do kung fu. Para impedi-lo, Po e os Cinco Furiosos precisam cruzar o país e derrotá-lo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/oDoxqekgain7WEHjoBN8BZIY6dY.jpg',
  },
  {
    title: 'A Lenda do Tesouro Perdido 2',
    subtitle: 'Livro dos Segredos.',
    storyline: 'Para provar a inocência de seu antepassado e encontrar a Cidade Perdida de Ouro, Ben Gates e sua equipe devem tecer seu caminho em direção a um livro misterioso e altamente guardado contendo séculos de segredos. Mas só há uma maneira de encontrá-lo: Ben deve sequestrar o presidente.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/uieqgufMTYPIq5Zcs5rfJ0b1eMb.jpg',
  },
  {
    title: 'A Liga Extraordinária',
    subtitle: 'Prepare-se para o extraordinário.',
    storyline: 'No final do século XIX a rainha Vitória nomeia uma legião de grandes nomes da época para combater um perigoso inimigo: um gênio do crime que deseja conquistar o planeta. Entre os convocados para enfrentá-lo estão Allan Quatermain, Mina Harker, Dorian Gray e o Dr. Jekyll.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/fQsSd5XYSGjn6TT2uSo2iG3VL9r.jpg',
  },
  {
    title: 'Uma linda mulher',
    subtitle: 'Os sonhos são para todos.',
    storyline: 'Magnata perdido pede ajuda uma prostituta que "trabalha" no Hollywood Boulevard e acaba contratando-a por uma semana. Neste período ela se transforma em uma elegante jovem para poder acompanhá-lo em seus compromissos sociais, mas os dois começam a se envolver e a relação patrão/empregado se modifica para um relacionamento entre homem e mulher.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/1lx3rr6yufCpSPVdkfUueqHstiw.jpg',
  },
  {
    title: 'Mensagem para voce',
    subtitle: 'Alguém que você já cruzou na rua pode ser o amor da sua vida.',
    storyline: 'Dona de uma pequena livraria, Kathleen Kelly odeia Joe Fox, proprietário da gigantesca rede de livrarias Foxbooks. Quando os dois se conhecem através da internet, iniciam um romance online intenso e anônimo. Um dia, Joe fica sabendo que a encantadora mulher é sua rival de negócios.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/lfir1ogD5WEEqIFr07ymKSHMdkO.jpg',
  },
  {
    title: 'Uma mente brilhante',
    subtitle: 'Ele viu o mundo de uma maneira que ninguém poderia imaginar.',
    storyline: 'John Nash (Russell Crowe) é um gênio da matemática que, aos 21 anos, formulou um teorema que provou sua genialidade e o tornou aclamado no meio onde atuava. Mas aos poucos o belo e arrogante Nash se transforma em um sofrido e atormentado homem, que chega até mesmo a ser diagnosticado como esquizofrênico pelos médicos que o tratam. Porém, após anos de luta para se recuperar, ele consegue retornar à sociedade e acaba sendo premiado com o Nobel.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/emI82b8ndgDAdqFOWfVZId5EkID.jpg',
  },
  {
    title: 'Os mercenários',
    subtitle: 'Escolha sua Arma',
    storyline: 'Um grupo de mercenários, liderado por Barney Ross, e seus homens de confiança aceitam uma missão que parece ser rotineira: uma operação secreta, a mando da Igreja, para invadir o país sul-americano de Vilena e derrubar seu ditador. Não demora muito para o grupo perceber que a missão é uma operação suicida. Presos em uma perigosa teia de traições, mas sabendo que um inocente está em perigo, Barney e seus homens decidem finalizar o trabalho.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/tTfRV9lOBi3YDJpYXqbj4Ai04g2.jpg',
  },
  {
    title: 'Mortal Kombat (1995)',
    subtitle: 'Nada neste mundo te preparou para esse combate.',
    storyline: 'Os planetas estão desalinhados. Para deter as forças do mal e salvar a humanidade, Lord Rayden, o protetor da Terra, escolhe as três pessoas capazes de vencer o Mortal Kombat, disputado pelos melhores lutadores do universo.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/aVotlc03uy62YJUFGxlQUF7FZXV.jpg',
  },
  {
    title: 'Mortal Kombat',
    subtitle: 'Get over here.',
    storyline: 'O lutador de MMA Cole Young deve treinar para liberar seu verdadeiro poder para unir-se aos maiores campeões mundiais contra inimigos da Exoterra em uma batalha decisiva pelo universo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/w8BVC3qrCWCiTHRz4Rft12dtQF0.jpg',
  },
  {
    title: 'Motoqueiro Fantasma',
    subtitle: 'Sua maldição se tornou seu poder.',
    storyline: 'Johnny Blaze trabalha como dublê e piloto de motocicleta. Há muito tempo ele fez um pacto com Mefisto para proteger as duas pessoas que mais amava: seu pai, Barton, e sua namorada de adolescência, Roxanne Simpson. Em troca Johnny se transforma à noite no Motoqueiro Fantasma, o justiceiro de alguns demônios bastante cruéis. Forçado a obedecer as ordens de Mefisto, Johnny decide enfrentá-lo de forma a usar sua maldição para proteger pessoas inocentes.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/vVGVlwRrvVgLPE98rwo8jo3QC2b.jpg',
  },
  {
    title: 'Onze Homens e um Segredo',
    subtitle: 'Você está dentro ou fora?',
    storyline: 'O golpista Danny Ocean está de volta à ativa após uma breve estada na penitenciária de New Jersey, e pretende recomeçar com o mais ambicioso roubo de sua carreira. E para tanto, vai precisar do melhor time que U$$ 150 milhões e o desejo pelo desafio de roubar três dos maiores cassinos de Las Vegas possam comprar. O primeiro a se juntar à equipe é Rusty Ryan, que atualmente trapaceia em rodas de pôquer com jovens atores de Hollywood.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/8NbSiE9xnymrcMEfiUbSM9it7hq.jpg',
  },
  {
    title: 'O Planeta do Tesouro',
    subtitle: 'Encontre seu lugar no universo.',
    storyline: 'Versão animada da Disney de “Ilha do Tesouro”, mas passando-se no espaço. Jim Hawkins é um adolescente rebelde sem muita perspectiva de futuro, até receber um mapa que o fará percorrer o espaço em sua nave com uma tripulação de personagens característicos da empresa. Afundou na bilheteria e foi um dos responsáveis pela decisão de Disney de não lançar mais filmes de animação convencional.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/4GJnKM1CLylmp8phkyiITiwu7L.jpg',
  },
  {
    title: 'O Rei Leão',
    subtitle: 'A maior aventura da vida, é descobrir o seu lugar no ciclo da vida.',
    storyline: 'Mufasa, o Rei Leão, e a rainha Sarabi apresentam ao reino o herdeiro do trono, Simba. O recém-nascido recebe a bênção do sábio babuíno Rafiki, mas ao crescer é envolvido nas artimanhas de seu tio Scar, o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/8aIvm8OaJISOpVTt7rMIh7X35G5.jpg',
  },
  {
    title: 'O Resgate do soldado Ryan',
    subtitle: 'A missão é um homem.',
    storyline: 'Ao desembarcar na Normandia, no dia 6 de junho de 1944, capitão Miller recebe a missão de comandar um grupo do segundo batalhão para o resgate do soldado James Ryan, caçula de quatro irmãos, dentre os quais três morreram em combate. Por ordens do chefe George C. Marshall, eles precisam procurar o soldado e garantir o seu retorno, com vida, para casa.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/iZ3jDTycla1JasNg6h7Gg1sEIys.jpg',
  },
  {
    title: 'Robin Hood',
    subtitle: 'Até cordeiros se tornarem leões.',
    storyline: 'Robin Longstride (Russell Crowe) integra o exército do rei Ricardo Coração de Leão (Danny Huston), que está em plenas cruzadas. Após a morte do rei, ele consegue escapar juntamente com alguns companheiros. Em sua tentativa de fuga eles encontram Sir Robert Loxley (Douglas Hodge), que tinha por missão levar a coroa do rei a Londres. Loxley foi atacado por Godfrey (Mark Strong), um inglês que serve secretamente aos interesses do rei Filipe, da França. À beira da morte, Loxley pede a Robin que entregue a seu pai uma espada tradicional da família. Ele aceita a missão e, vestido como se fosse um cavaleiro real, parte para Londres. Após entregar a coroa ao príncipe João (Oscar Isaac), que é nomeado rei, Robin parte para Nottingham. Lá conhece Sir Walter (Max von Sydow) e Marion (Cate Blanchett), respectivamente pai e esposa de Loxley.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/cCzqyuZxvJ38E8DXMbW9q4qgUVa.jpg',
  },
  {
    title: 'RollerBall',
    subtitle: 'Em um futuro não muito distante, as guerras não existirão mais. Mas HAVERÁ... O Jogo.',
    storyline: 'Em uma sociedade futurista, as corporações têm substituído países e existe um jogo recreativo e violento conhecido como"Rollerball", o qual é controlado pelas organizações e jogado em todo o mundo. Em um determinado momento, Jonathan E., um dos jogadores, decide lutar por sua liberdade e deixa o controle da corporação em perigo.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/vQIdxj2PYiUupmnhxUgcSkKIu11.jpg',
  },
  {
    title: 'Vingança de Scorpion',
    subtitle: 'Matar sua família foi um erro',
    storyline: 'Após o massacre cruel de sua família pelo mercenário Sub-Zero, Hanzo Hasashi é exilado no tortuoso Netherrealm, lá, em troca de sua servidão ao sinistro Quan Chi, ele tem a chance de vingar sua família - e ressuscita como Scorpion, uma alma perdida e vingativa. De volta ao Earthrealm, Lord Raiden reúne uma equipe de guerreiros de elite - o monge Shaolin Liu Kang, a oficial das Forças Especiais Sonya Blade e o ator de ação Johnny Cage - um grupo improvável de heróis com uma chance de salvar a humanidade. Para fazer isso, eles devem derrotar a horda de gladiadores do Outworld de Shang Tsung e vencer o torneio Mortal Kombat.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/zO5913BWcWYrhgACNpaaw9CCycX.jpg',
  },
  {
    title: 'Spawn',
    subtitle: 'Nascido no inferno. Jurando justiça.',
    storyline: 'O assassino do governor Al Simmons é morto depois de ser traído por seu chefe, Jason Wynn. Ao chegar no inferno, Simmons recebe uma oferta para retornar à Terra se ele estiver disposto a liderar um exército do mal. Ele aceita e é reencarnado como um Hellspawn, uma versão horrivelmente distorcida de sua antiga personalidade. No entanto, Spawn serve como uma força do bem para o desespero de capanga do Diabo, um palhaço mau.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/653tt7EeQZ2LqLMeiGApxkdsKB2.jpg',
  },
  {
    title: 'Tempestade - Planeta em Fúria',
    subtitle: 'Enfrente a tempestade.',
    storyline: 'Depois de uma série de desastres naturais sem precedentes ameaçar o planeta, os líderes mundiais se unem para criar uma rede complexa de satélites para controlar o clima mundial e manter todos em segurança. Porém, agora, algo deu errado – o sistema criado para proteger a Terra passou a atacá-la, dando início a uma corrida contra o tempo para descobrir a verdadeira ameaça, antes que uma tempestade de proporções globais devaste tudo… e todos em seu caminho.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/uGNyIpD9bTFVvXMaMOxo7RwNUSN.jpg',
  },
  {
    title: 'Top Gun - Ases Indomáveis',
    subtitle: 'Voe com o melhor dos melhores.',
    storyline: 'A escola naval de pilotos é onde o melhor dos melhores treinam para refinar suas habilidades de voo de elite. Quando o piloto Maverick é enviado para a escola, sua atitude irresponsável e comportamento arrogante o colocam em desacordo com os outros pilotos, especialmente Iceman. Porém Maverick não está apenas competindo para ser o piloto superior de caça, ele também está lutando pela atenção de sua bonita instrutora de voo, Charlotte Blackwood.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/dDrMtnVgtDeecIgNchb9F8JcO5w.jpg',
  },
  {
    title: 'Como Treinar seu Dragão',
    subtitle: 'Uma aventura vai mudar dois mundos',
    storyline: 'Soluço é um jovem viking que desafia a tradição, quando fica amigo de um dos mais mortais inimigos – um feroz dragão que ele chama de Banguela.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/spZbO7Ss6U9W5zSHjtH6FvXvCF7.jpg',
  },
  {
    title: 'Como Treinar seu Dragão 2',
    subtitle: 'O treinamento acaba, e começa a aventura!',
    storyline: 'Cinco anos após convencer os habitantes de seu vilarejo que os dragões não devem ser combatidos, Soluço convive com seu dragão Fúria da Noite, e estes animais integraram pacificamente a rotina dos moradores da ilha de Berk. Entre viagens pelos céus e corridas de dragões, Soluço descobre uma caverna secreta, onde centenas de novos dragões vivem. O local é protegido por Valka, mãe de Soluço, que foi afastada do filho quando ele ainda era um bebê. Juntos, eles precisarão proteger o mundo que conhecem do perigoso Drago Bludvist, que deseja controlar todos os dragões existentes.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/8oZdjpms0zkYQ1XAPpbzWYPtUnv.jpg',
  },
  {
    title: 'Trovão Azul',
    subtitle: 'Ele está lá fora.',
    storyline: 'O Trovão Azul é um helicóptero especialmente modificado para trabalho policial, criado para controlar rebeliões. O piloto da polícia que deve ser treinado para comandá-lo tem diferenças com o criador do projeto desde a época do Vietnã, e elas pioram.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ytHeRRetF23dgWJ1kxMt6WjAqRb.jpg',
  },
  {
    title: 'X-Men - Apocalipse',
    subtitle: 'Apenas os fortes sobreviverão.',
    storyline: 'Apocalipse, o primeiro mutante de todos, consegue retornar à vida após milhares de anos. Agora, ele sai à procura de seguidores para dominar o mundo. Caberá aos X-Men se unirem para impedir os planos do vilão e evitar uma catástofre mundial.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/a6OjCxF8DW9huIdAPshWJpO0ldx.jpg',
  },
  {
    title: 'X-Men',
    subtitle: '',
    storyline: 'Enquanto o senador Kelly se dirige a um comitê do Senado sobre a suposta ameaça mutante, aprendemos sobre a produção do filme X-Men.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/4FwbuT0NJwcHGRqRc3kpTjgj0jS.jpg',
  },
  {
    title: 'X-Men - Dias de um futuro esquecido',
    subtitle: 'Para salvar o futuro , eles devem alterar o passado',
    storyline: 'Convencido de que os mutantes são uma ameaça para a humanidade, o Dr. Bolivar Trask desenvolve os Sentinelas, gigantescos robôs, que os perseguem impiedosamente. Os poucos sobreviventes têm que viver escondidos. Entre eles está Wolverine, que viaja no tempo, rumo aos anos 1970, a fim de impedir que este futuro trágico para os mutantes se torne realidade.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/bUm0nSsTA6kfFfZHgNbNFisVe7M.jpg',
  },
  {
    title: 'X-Men - Origens Wolverine',
    subtitle: 'Testemunhe a origem.',
    storyline: 'Tentando esquecer seu passado sombrio, Logan, mais conhecido como Wolverine, parece ter encontrado o amor e a felicidade com Kayla Silverfox. Mas a paz de Logan é abalada quando Victor Creed, seu irmão cruel, assassina brutalmente Kayla. A sede de vingança de Logan o leva ao programa Arma X. Ele passa por um processo doloroso para fortalecer seus ossos com adamantium, o que o torna praticamente indestrutível.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/3xjVVXVXWU8qt1umkeTJd8sImBC.jpg',
  },
  {
    title: 'X-Men - Primeira Classe',
    subtitle: 'Testemunhe o começo.',
    storyline: 'No início dos anos 1960, durante o auge da Guerra Fria, um mutante chamado Charles Xavier conhece um mutante chamado Erik Lehnsherr. Apesar de suas origens muito diferentes - Charles cresceu em uma família rica enquanto Erik perdeu seus pais em Auschwitz -, os dois se tornam grandes amigos. Enquanto o mundo oscila à beira de uma guerra nuclear, Charles e Erik unem forças com outros mutantes para salvar a humanidade. No entanto, um acontecimento separa os dois amigos.',
    rating: 4.5,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/AqTCbMhG9X93sly2fvyiu6sHPIS.jpg',
  },
  {
    title: 'A Origem',
    subtitle: 'Sua mente é a cena do crime.',
    storyline: 'Um ladrão que rouba segredos corporativos por meio do uso da tecnologia de compartilhamento de sonhos, recebe a tarefa inversa de plantar uma ideia na mente de um Diretor Executivo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/ms1bJvwa4BJycBakQ7afcedGlwY.jpg',
  },
  {
    title: 'A Rocha',
    subtitle: 'O único que conseguiu escapar é também sua última chance.',
    storyline: 'Um general, herói na Guerra do Vietnã, e seus comandados se apoderam de poderosas armas químicas e se instalam na prisão de Alcatraz, com 81 reféns. De lá eles ameaçam disparar as armas sobre São Francisco se 100 milhões de dólares não forem pagos, sendo que grande parte desta quantia será para doar às famílias de soldados americanos que morreram em missões secretas e nunca foram reconhecidos pela pátria. Para combatê-los, um grupo de elite é mandado para a ilha e entre eles está um jovem especialista em armas bioquímicas e o único homem que escapou do presídio, só que agora ele tem de entrar e, se possível, completar sua missão e sair vivo.',
    rating: 4.8,
    imagePath: 'https://www.themoviedb.org/t/p/w220_and_h330_face/eFPh6GQMQROAe6y1KQuL9f0TFRX.jpg',
  },
]

export default movies;
